##############################
### Bot Configuration File ###
##############################

# Insert your discord bot token
DISCORD_TOKEN = "INSERT_TOKEN"

# Log Level
# Available variant: DEBUG, INFO
[LOG_LEVEL]
STREAM = "INFO"
FILE   = "DEBUG"
HTTP   = "INFO"
CLIENT = "INFO"
GTWAY  = "INFO"
